name: CD

on:
  # push:
  #   tags:
  #     - "*.*.*"
  workflow_dispatch:

jobs:
  release:
    uses: douglaslassance/catapult/.github/workflows/release.yml@09ea01657cb3dad25f2a70b2e02dc4f85ae2e687
    secrets: inherit
    with:
      channels: "s3,homebrew,appstore"
