name: CD

on:
  # push:
  #   tags:
  #     - "*.*.*"
  workflow_dispatch:

jobs:
  release:
    uses: douglaslassance/catapult/.github/workflows/release.yml@bee1864e75ff0197b8d4418825954bd7f7f8c470
    secrets: inherit
    with:
      channels: "s3,homebrew,appstore"
