name: CD

on:
  # push:
  #   tags:
  #     - "*.*.*"
  workflow_dispatch:

jobs:
  release:
    uses: douglaslassance/catapult/.github/workflows/release.yml@95d1409b434eca0f03c156b6e2eb450d4e347f5e
    secrets: inherit
    with:
      channels: "s3,homebrew,appstore"
